[package]
name = "yield-optimizer"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "yield-optimizer"
path = "src/yield_optimizer.rs"

[dependencies]
polkavm-derive = "0.27.0"

[dependencies.uapi]
package = "pallet-revive-uapi"
version = "0.7.0"
default-features = false
features = ["unstable-hostfn"]

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
