// Deployed to Polkadot Hub Testnet (chain 420420417)
export const POLKAVAULT_ADDRESS = "0x64D3EfbAde442779c68972D5079861Bcf16722E6" as const;

export const POLKAVAULT_ABI = [
  // ── Write ────────────────────────────────────────────────────
  {
    type: "function",
    name: "setKeeperFee",
    inputs: [{ name: "bps", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "requestWithdraw",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimWithdrawal",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "compound",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sendCrossChain",
    inputs: [
      { name: "shares", type: "uint256" },
      { name: "destAccount", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "payable",
  },

  // ── Read ──────────────────────────────────────────────────────
  {
    type: "function",
    name: "uniqueDepositors",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "keeperFeeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastApyBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastCompoundTime",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastCompoundRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getNominators",
    inputs: [],
    outputs: [{ name: "", type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nominateValidators",
    inputs: [{ name: "targets", type: "bytes32[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "yieldOptimizer",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setYieldOptimizer",
    inputs: [{ name: "optimizer", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ValidatorsNominated",
    inputs: [{ name: "targets", type: "bytes32[]", indexed: false }],
  },
  {
    type: "function",
    name: "getVaultStats",
    inputs: [],
    outputs: [
      { name: "rate",      type: "uint256" },
      { name: "staked",    type: "uint256" },
      { name: "unbonding", type: "uint256" },
      { name: "supply",    type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserPosition",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "stDotBalance", type: "uint256" },
      { name: "dotValue",     type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getWithdrawRequests",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "dot",         type: "uint256" },
          { name: "claimableAt", type: "uint256" },
          { name: "claimed",     type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "exchangeRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sharesForDot",
    inputs: [{ name: "dot", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dotForShares",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalStaked",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unbondingPeriod",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "xcmFeeAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewXcmMessage",
    inputs: [
      { name: "shares",      type: "uint256" },
      { name: "destAccount", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },

  // ── Events ────────────────────────────────────────────────────
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from",  type: "address", indexed: true  },
      { name: "to",    type: "address", indexed: true  },
      { name: "value", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { name: "user",  type: "address", indexed: true  },
      { name: "dot",   type: "uint256", indexed: false },
      { name: "stDot", type: "uint256", indexed: false },
      { name: "rate",  type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "WithdrawRequested",
    inputs: [
      { name: "user",        type: "address", indexed: true  },
      { name: "stDot",       type: "uint256", indexed: false },
      { name: "dot",         type: "uint256", indexed: false },
      { name: "claimableAt", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "WithdrawClaimed",
    inputs: [
      { name: "user", type: "address", indexed: true  },
      { name: "dot",  type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Compounded",
    inputs: [
      { name: "rewards",        type: "uint256", indexed: false },
      { name: "newRate",        type: "uint256", indexed: false },
      { name: "newTotalStaked", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "KeeperRewarded",
    inputs: [
      { name: "keeper",     type: "address", indexed: true  },
      { name: "fee",        type: "uint256", indexed: false },
      { name: "compounded", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "KeeperFeeUpdated",
    inputs: [{ name: "feeBps", type: "uint256", indexed: false }],
  },
  {
    type: "event",
    name: "SentCrossChain",
    inputs: [
      { name: "user", type: "address", indexed: true  },
      { name: "dot",  type: "uint256", indexed: false },
      { name: "dest", type: "bytes32", indexed: false },
    ],
  },
] as const;
